[profile.release]
panic = 'unwind' # reduce binary size

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
  'node',
  'runtime',
  'runtime/integration-tests',
  'primitives',
  'pallets/fluent-fee',
  'pallets/contract-asset-registry',
  'pallets/currencies',
] 
resolver = "2" # use the new resolver for better dependency resolution
