[profile.release]
panic = 'unwind' # reduce binary size

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
  'node',
  'runtime',
  'runtime/integration-tests',
  'dummy-runtime',
  'primitives',
  'pallets/rando',
  'pallets/evm-hydro',
  'pallets/fluent-fee',
  'precompiles/rando',
  'precompiles/utils',
]

resolver = "2" # use the new resolver for better dependency resolution

[patch.'https://github.com/ultrastable-money/frontier']
ethereum = {version = "0.10.0"}
