[profile.release]
panic = 'unwind' # reduce binary size

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
  'node',
  'runtime',
  'runtime/integration-tests',
  'primitives',
  'pallets/rando',
  'pallets/evm-hydro',
  'pallets/fluent-fee',
  'precompiles/rando',
  'precompiles/utils',
  'precompiles/native-asset',
  'precompiles/erc20',
  'pallets/reverse-evm-call',
] 
resolver = "2" # use the new resolver for better dependency resolution
