use crate::{weights::pallet_balances::WeightInfo, Event, Runtime, System};
use frame_support::parameter_types;

use primitives::Balance;

parameter_types! {
	pub const ExistentialDeposit: u128 = 500;
	pub const MaxLocks: u32 = 50;
}

impl pallet_balances::Config for Runtime {
	type MaxLocks = MaxLocks;
	type MaxReserves = ();
	type ReserveIdentifier = [u8; 8];
	/// The type for recording an account's balance.
	type Balance = Balance;
	/// The ubiquitous event type.
	type Event = Event;
	type DustRemoval = ();
	type ExistentialDeposit = ExistentialDeposit;
	type AccountStore = System;

	// we can either:
	// 1. use SubstrateWeight recomended by substrate on standard hardware
	// 2. use WeightInfo generated by benchmark running on our target hardware
	type WeightInfo = WeightInfo<Runtime>;
}
