[package]
edition = "2021"
name = "integration-tests"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# hydro-chain's primitives
primitives = {path = "../../primitives", default-features = false}

# runtime's basic pallet impl
pallet-aura = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
pallet-balances = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
pallet-fluent-fee = {path = "../../pallets/fluent-fee", default-features = false}

pallet-grandpa = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
pallet-rando = {version = "0.1.0", path = "../../pallets/rando"}
pallet-scheduler = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
pallet-sudo = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
pallet-timestamp = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
pallet-transaction-payment = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
pallet-transaction-payment-rpc-runtime-api = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}

# orml
orml-currencies = {git = 'https://github.com/ultrastable-money/open-runtime-module-library.git', version = "0.4.1-dev", branch = "hydro-dep-master"}
orml-tokens = {git = 'https://github.com/ultrastable-money/open-runtime-module-library.git', version = "0.4.1-dev", branch = "hydro-dep-master"}
orml-traits = {git = 'https://github.com/ultrastable-money/open-runtime-module-library.git', version = "0.4.1-dev", branch = "hydro-dep-master"}

# evm related
evm-hydro = {path = "../../pallets/evm-hydro", default-features = false}
native-asset-precompile = {path = "../../precompiles/native-asset", default-features = false}
pallet-evm = {git = 'https://github.com/ultrastable-money/frontier.git', branch = "hydro-dep-master"}
pallet-evm-precompile-dispatch = {git = 'https://github.com/ultrastable-money/frontier.git', branch = "hydro-dep-master"}
pallet-evm-precompile-modexp = {git = 'https://github.com/ultrastable-money/frontier.git', branch = "hydro-dep-master"}
pallet-evm-precompile-sha3fips = {git = 'https://github.com/ultrastable-money/frontier.git', branch = "hydro-dep-master"}
pallet-evm-precompile-simple = {git = 'https://github.com/ultrastable-money/frontier.git', branch = "hydro-dep-master"}
pallet-rando-precompile = {path = "../../precompiles/rando", default-features = false}

precompile-utils = {path = "../../precompiles/utils", default-features = false}

# interface for pallet build with frame
frame-benchmarking = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev', optional = true}
frame-executive = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
frame-support = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
frame-system = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
frame-system-benchmarking = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev', optional = true}
frame-system-rpc-runtime-api = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}

# sp stands for substrate-primitives, used across node and runtime
sp-api = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-io = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}

sp-block-builder = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-consensus-aura = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '0.10.0-dev'}
sp-core = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-inherents = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-offchain = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-runtime = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-session = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-std = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}

sp-transaction-pool = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}
sp-version = {git = 'https://github.com/ultrastable-money/substrate.git', branch = "hydro-dep-2021-11-1", version = '4.0.0-dev'}

# parity SCALE codec
codec = {features = ['derive'], package = 'parity-scale-codec', version = '2.0.0'}
hex-literal = {version = '0.3.1'}
scale-info = {features = ['derive'], version = '1.0'}

# runtime
hydro-runtime = {path = "../"}

# build dependency for the wasm runtime
[build-dependencies.substrate-wasm-builder]
branch = "hydro-dep-2021-11-1"
git = 'https://github.com/ultrastable-money/substrate.git'
version = '5.0.0-dev'

[features]
default = ["std"]
evm = []
std = []
