[package]
edition = "2021"
name = "hydro-node"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hydro-node"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '3.0.0'

[dependencies]
# hydro chain primitives
primitives = {path = "../primitives"}

# hydro chain runtime
hydro-runtime = {path = "../runtime", optional = true}

sc-basic-authorship = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-cli = {features = ['wasmtime'], git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-client-api = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sc-consensus = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-consensus-aura = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-executor = {features = ['wasmtime'], git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-finality-grandpa = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-rpc = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sc-rpc-api = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-service = {features = ['wasmtime'], git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sc-telemetry = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sc-transaction-pool = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sc-transaction-pool-api = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}

# substrate primitives
sp-api = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sp-block-builder = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sp-blockchain = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sp-consensus = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sp-consensus-aura = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '0.10.0-dev'}
sp-core = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sp-finality-grandpa = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
sp-timestamp = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}

substrate-frame-rpc-system = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}

pallet-transaction-payment-rpc = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}

# requird for benchmark cli-parsing and conduct runtime-benchmark
frame-benchmarking = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}
frame-benchmarking-cli = {git = 'https://github.com/ultrastable-money/substrate.git', tag = 'monthly-2021-11-1', version = '4.0.0-dev'}

dummy-runtime = {path = "../dummy_runtime", optional = true}
jsonrpc-core = "18.0.0"
structopt = "0.3.25"

[features]
default = [
  "hydro-runtime",
]
runtime-benchmarks = [
  "hydro-runtime/runtime-benchmarks",
]
test_runtime = [
  "dummy-runtime",
]
