[package]
edition = "2021"
name = "hydro-node"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hydro-node"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies.substrate-build-script-utils]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '3.0.0'

[dependencies]
jsonrpc-core = "18.0.0"
runtime = {path = "../runtime"}
structopt = "0.3.25"

[dependencies.sc-cli]
features = ['wasmtime']
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '0.10.0-dev'

[dependencies.sc-service]
features = ['wasmtime']
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '0.10.0-dev'

[dependencies.sc-rpc]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[dependencies.sc-rpc-api]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '0.10.0-dev'

[dependencies.sp-api]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[dependencies.sp-block-builder]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[dependencies.sp-blockchain]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[dependencies.substrate-frame-rpc-system]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[dependencies.sc-transaction-pool-api]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[dependencies.sc-transaction-pool]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[dependencies.sc-executor]
features = ['wasmtime']
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '0.10.0-dev'

[dependencies.sc-consensus]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '0.10.0-dev'

[dependencies.sc-finality-grandpa]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '0.10.0-dev'

[dependencies.sc-consensus-aura]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '0.10.0-dev'

[dependencies.sc-telemetry]
git = 'https://github.com/ultrastable-money/substrate.git'
tag = 'monthly-2021-11-1'
version = '4.0.0-dev'

[features]
