// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_fee_enablement
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-08-14, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: ``, CPU: ``
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/laguna-node
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_fee_enablement
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// ./pallets/fee-enablement/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_fee_enablement.
pub trait WeightInfo {
	fn onboard_asset() -> Weight;
	fn enable_asset() -> Weight;
	fn disable_asset() -> Weight;
}

/// Weights for pallet_fee_enablement using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: FeeEnablement FeeAssets (r:0 w:1)
	fn onboard_asset() -> Weight {
		(3_000_000 as Weight).saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: FeeEnablement FeeAssets (r:1 w:1)
	fn enable_asset() -> Weight {
		(7_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: FeeEnablement FeeAssets (r:1 w:1)
	fn disable_asset() -> Weight {
		(8_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: FeeEnablement FeeAssets (r:0 w:1)
	fn onboard_asset() -> Weight {
		(3_000_000 as Weight).saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: FeeEnablement FeeAssets (r:1 w:1)
	fn enable_asset() -> Weight {
		(7_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: FeeEnablement FeeAssets (r:1 w:1)
	fn disable_asset() -> Weight {
		(8_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}
